#!/usr/bin/env php
<?php

    if( !@file_exists( 'bootstrap.php' ) )
    {
        echo 'Couldn\'t find bootstrap.php in tests directory.';
        exit;
    }

    include_once( 'bootstrap.php' );

    use \phs\PHS_cli;
    use \phs\tests\phs\phs_tests;

    if( !PHS_cli::running_in_cli() )
    {
        echo PHS_cli::_t( 'This script must be run in a CLI environment.' )."\n";
        exit;
    }

    if( !($phs_tests = phs_tests::get_instance()) )
    {
        $error_msg = phs_tests::st_cli_color( phs_tests::_t( 'ERROR' ), 'red' ).': ';
        if( phs_tests::st_has_error() )
            $error_msg .= phs_tests::st_get_simple_error_message();
        else
            $error_msg .= PHS_cli::_t( 'Error obtaining phs_tests class instance.' );

        echo $error_msg."\n";

        exit;
    }

    $phs_tests->_echo( $phs_tests::_t( 'Script executed using PHP version: %s', $phs_tests->cli_color( trim( PHP_VERSION ), 'red' ) ) );

    $phs_tests->run();

