<?php

// autoload_static.php @generated by Composer
namespace Composer\Autoload;

class ComposerStaticInit464c65470863f27af5a068159e160746
{
    public static $prefixLengthsPsr4 = [
        'c' => [
            'chillerlan\\Settings\\' => 20,
            'chillerlan\\QRCode\\'   => 18,
        ],
    ];

    public static $prefixDirsPsr4 = [
        'chillerlan\\Settings\\' => [
            0 => __DIR__.'/..'.'/chillerlan/php-settings-container/src',
        ],
        'chillerlan\\QRCode\\' => [
            0 => __DIR__.'/..'.'/chillerlan/php-qrcode/src',
        ],
    ];

    public static $classMap = [
        'Composer\\InstalledVersions' => __DIR__.'/..'.'/composer/InstalledVersions.php',
    ];

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function() use ($loader) {
            $loader->prefixLengthsPsr4 = self::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = self::$prefixDirsPsr4;
            $loader->classMap = self::$classMap;
        }, null, ClassLoader::class);
    }
}
