<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit464c65470863f27af5a068159e160746
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__.'/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__.'/platform_check.php';

        spl_autoload_register(['ComposerAutoloaderInit464c65470863f27af5a068159e160746', 'loadClassLoader'], true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(['ComposerAutoloaderInit464c65470863f27af5a068159e160746', 'loadClassLoader']);

        require __DIR__.'/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInit464c65470863f27af5a068159e160746::getInitializer($loader));

        $loader->register(true);

        return $loader;
    }
}
