<?php

namespace phs\system\core\events\routing;

use phs\libraries\PHS_Event;

class PHS_Event_Url_rewrite extends PHS_Event
{
    /**
     * @inheritdoc
     */
    public function supports_background_listeners() : bool
    {
        return false;
    }

    protected function _input_parameters() : array
    {
        return [
            // Received parameters
            'route'    => [],
            'args'     => [],
            'raw_args' => [],

            // URL generated by PHS
            'stock_args'         => [],
            'stock_query_string' => [],
            'stock_url'          => '',
        ];
    }

    /**
     * @inheritdoc
     */
    protected function _output_parameters() : array
    {
        return [
            // Resulting URL
            'url' => '',
        ];
    }
}
